<?php
/**
 * Localized data
 *
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
 * 
 */
/**
 * @author Erwan Taloc <erwan.taloc@combodo.com>
 * @author Romain Quetiez <romain.quetiez@combodo.com>
 * @author Denis Flaven <denis.flaven@combodo.com>
 *
 */
Dict::Add('PT BR', 'Brazilian', 'Brazilian', [
	'Approval:Abort:Explain' => 'Você pediu para <b>bypass</b> o processo de aprovação. Isso interromperá o processo e nenhum dos aprovadores poderão responder.',
	'Approval:Action-Abort' => 'Ignorar o processo de aprovação',
	'Approval:Action-Approve' => 'Aprovar',
	'Approval:Action-ApproveOrReject' => 'Aprovar ou Rejeitar',
	'Approval:Action-Reject' => 'Rejeitar',
	'Approval:Approved-By' => 'Aprovado por %1$s',
	'Approval:Approved-On-behalf-of' => 'Aprovado por %1$s em nome de %2$s',
	'Approval:Comment-Label' => 'Seu comentário',
	'Approval:Comment-Mandatory' => 'Um comentário deve ser inserido para rejeição',
	'Approval:Comment-Reused' => 'Resposta já feita no passo %1$s, com comentário "%2$s"',
	'Approval:Comment-Tooltip' => 'Obrigatório para rejeição, opcional para aprovação',
	'Approval:Form:AlreadyApproved' => 'Desculpe, o processo já foi concluído com o resultado: aprovado.',
	'Approval:Form:AlreadyRejected' => 'Desculpe, o processo já foi concluído com o resultado: rejeitado.',
	'Approval:Form:AnswerGivenBy' => 'Desculpe, a resposta já foi dada por \'%1$s\'',
	'Approval:Form:AnswerRecorded-Approved' => 'Sua resposta foi registrada. O processo de aprovação agora está completo com o resultado APROVADO.',
	'Approval:Form:AnswerRecorded-Continue' => 'Sua resposta foi registrada. O processo de aprovação continua.',
	'Approval:Form:AnswerRecorded-Rejected' => 'Sua resposta foi registrada. O processo de aprovação agora está completo com o resultado REJEITADO.',
	'Approval:Form:ApproverDeleted' => 'Desculpe, o registro correspondente a sua identidade foi excluído',
	'Approval:Form:ObjectDeleted' => 'Desculpe, o objeto da aprovação foi excluído',
	'Approval:Form:Ref' => 'Processo de aprovação para %1$s',
	'Approval:Form:StepApproved' => 'Desculpe, esta fase foi concluída com o resultado: aprovado. O processo de aprovação continua...',
	'Approval:Form:StepRejected' => 'Desculpe, esta fase foi concluída com o resultado: rejeitado. O processo de aprovação continua...',
	'Approval:Form:Title' => 'Aprovação',
	'Approval:Ongoing-FilterMyApprovals' => 'Mostrar itens para os quais minha aprovação está sendo exigida.',
	'Approval:Ongoing-NothingCurrently' => 'Não há aprovação em andamento.',
	'Approval:Ongoing-Title' => 'Aprovações em andamento',
	'Approval:Ongoing-Title+' => 'Processos de aprovação para objetos de classe %1$s',
	'Approval:Portal:Btn:Approve' => 'Aprovar',
	'Approval:Portal:Btn:Reject' => 'Rejeitar',
	'Approval:Portal:CommentPlaceholder' => '',
	'Approval:Portal:CommentTitle' => 'Comentário de aprovação (obrigatório em caso de rejeição)',
	'Approval:Portal:Dlg:Approve' => 'Por favor, confirme que você deseja aprovar <em><span class="approval-count">?</span></em> item(ns)',
	'Approval:Portal:Dlg:ApproveOne' => 'Por favor, confirme que você deseja aprovar este item.',
	'Approval:Portal:Dlg:Btn:Approve' => 'Aprovar!',
	'Approval:Portal:Dlg:Btn:Reject' => 'Rejeitar!',
	'Approval:Portal:Dlg:Reject' => 'Por favor, confirme que você deseja rejeitar <em><span class="approval-count">?</span></em> item(ns)',
	'Approval:Portal:Dlg:RejectOne' => 'Por favor, confirme que você deseja rejeitar este item.',
	'Approval:Portal:NoItem' => 'No momento, não há nenhum item esperando sua aprovação',
	'Approval:Portal:Success' => 'Seu feedback foi gravado.',
	'Approval:Portal:Title' => 'Itens aguardando sua aprovação',
	'Approval:Portal:Title+' => 'Por favor selecione os itens para aprovar e usar os botões localizados na parte inferior da página',
	'Approval:Rejected-By' => 'Rejeitado %1$s',
	'Approval:Rejected-On-behalf-of' => 'Rejeitado por %1$s em nome de %2$s',
	'Approval:Remind-Btn' => 'Enviar um lembrete...',
	'Approval:Remind-DlgBody' => 'Os seguintes contatos serão notificados novamente:',
	'Approval:Remind-DlgTitle' => 'Enviar um lembrete',
	'Approval:ReminderDone' => 'Um lembrete foi enviado para %1$d pessoa(as).',
	'Approval:Tab:End' => 'Fim',
	'Approval:Tab:End-Abort' => 'O processo de aprovação foi ignorado por %1$s at %2$s',
	'Approval:Tab:Error' => 'Um erro ocorreu durante o processo de aprovação: %1$s',
	'Approval:Tab:Start' => 'Início',
	'Approval:Tab:StepEnd-Condition-FirstApprove' => 'Esta etapa termina na primeira aprovação, ou se 100% rejeitado',
	'Approval:Tab:StepEnd-Condition-FirstReject' => 'Esta etapa termina na primeira rejeição, ou se 100% aprovado',
	'Approval:Tab:StepEnd-Condition-FirstReply' => 'Esta etapa termina na primeira resposta',
	'Approval:Tab:StepEnd-Limit' => 'Limite de tempo (resultado implícito)',
	'Approval:Tab:StepEnd-Theoretical' => 'Limite de tempo teórico (duração limitada a %1$s mn)',
	'Approval:Tab:StepSumary-Idle' => 'Não iniciado',
	'Approval:Tab:StepSumary-KO' => 'Rejeitado',
	'Approval:Tab:StepSumary-KO-Timeout' => 'Rejeitado (timeout)',
	'Approval:Tab:StepSumary-OK' => 'Aprovado',
	'Approval:Tab:StepSumary-OK-Timeout' => 'Aprovado (timeout)',
	'Approval:Tab:StepSumary-Ongoing' => 'Esperando por respostas',
	'Approval:Tab:StepSumary-Skipped' => 'Pulou',
	'Approval:Tab:Title' => 'Status de aprovação',
	'Class:ActionEmailApprovalRequest' => 'Pedido de aprovação por e-mail',
	'Class:ActionEmailApprovalRequest/Attribute:subject_reminder' => 'Assunto (lembrete)',
	'Class:ActionEmailApprovalRequest/Attribute:subject_reminder+' => 'Assunto do e-mail no caso de um lembrete ser enviado',
	'Class:ApprovalScheme' => 'ApprovalScheme~~',
	'Class:ApprovalScheme+' => '~~',
	'Class:ApprovalScheme/Attribute:abort_comment' => 'Abort comment~~',
	'Class:ApprovalScheme/Attribute:abort_comment+' => '~~',
	'Class:ApprovalScheme/Attribute:abort_date' => 'Abort date~~',
	'Class:ApprovalScheme/Attribute:abort_date+' => '~~',
	'Class:ApprovalScheme/Attribute:abort_user_id' => 'Abort user id~~',
	'Class:ApprovalScheme/Attribute:abort_user_id+' => '~~',
	'Class:ApprovalScheme/Attribute:current_step' => 'Current step~~',
	'Class:ApprovalScheme/Attribute:current_step+' => '~~',
	'Class:ApprovalScheme/Attribute:ended' => 'Ended~~',
	'Class:ApprovalScheme/Attribute:ended+' => '~~',
	'Class:ApprovalScheme/Attribute:label' => 'Label~~',
	'Class:ApprovalScheme/Attribute:label+' => '~~',
	'Class:ApprovalScheme/Attribute:last_error' => 'Last error~~',
	'Class:ApprovalScheme/Attribute:last_error+' => '~~',
	'Class:ApprovalScheme/Attribute:obj_class' => 'Obj class~~',
	'Class:ApprovalScheme/Attribute:obj_class+' => '~~',
	'Class:ApprovalScheme/Attribute:obj_key' => 'Obj key~~',
	'Class:ApprovalScheme/Attribute:obj_key+' => '~~',
	'Class:ApprovalScheme/Attribute:started' => 'Started~~',
	'Class:ApprovalScheme/Attribute:started+' => '~~',
	'Class:ApprovalScheme/Attribute:status' => 'Status~~',
	'Class:ApprovalScheme/Attribute:status+' => '~~',
	'Class:ApprovalScheme/Attribute:status/Value:accepted' => 'Accepted~~',
	'Class:ApprovalScheme/Attribute:status/Value:accepted+' => '~~',
	'Class:ApprovalScheme/Attribute:status/Value:ongoing' => 'Ongoing~~',
	'Class:ApprovalScheme/Attribute:status/Value:ongoing+' => '~~',
	'Class:ApprovalScheme/Attribute:status/Value:rejected' => 'Rejected~~',
	'Class:ApprovalScheme/Attribute:status/Value:rejected+' => '~~',
	'Class:ApprovalScheme/Attribute:steps' => 'Steps~~',
	'Class:ApprovalScheme/Attribute:steps+' => '~~',
	'Class:ApprovalScheme/Attribute:timeout' => 'Timeout~~',
	'Class:ApprovalScheme/Attribute:timeout+' => '~~',
	'Class:TriggerOnApprovalRequest' => 'Disparar (quando uma aprovação é solicitada)',
	'Class:TriggerOnApprovalRequest+' => 'Disparar no pedido de aprovação',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request' => 'Send request to~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request+' => '~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request/Value:approvers' => 'Approvers only~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request/Value:approvers+' => '~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request/Value:both' => 'Both approvers and substitutes~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request/Value:both+' => '~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request/Value:substitutes' => 'Substitutes only~~',
	'Class:TriggerOnApprovalRequest/Attribute:target_approval_request/Value:substitutes+' => '~~',
]);
